export enum ENUM_EFFECT_TAG {
	NO_EFFECT = 'NO_EFFECT',
	UPDATE = 'UPDATE',
	PLACEMENT = 'PLACEMENT',
	DELETION = 'DELETION',
	REPLACE = 'REPLACE',
}

export enum ENUM_NODE_TYPE {
	TEXT_NODE = 'TEXT_NODE',
}
